### ISSUE TITLE
Adding multiple ACs

### ISSUE THREAD

**Issue by Nasserish** [arthurkrupa/gree-hvac-mqtt-bridge#11]
Let me start by thanking you for this absolutely great add-on, which was my reason for buying Gree ACs. I have managed to add one of the ACs and it's working great, but I'm trying to figure out the configuration for adding three ACs ?

Your help is much appreciated..

Thanks,

**Comment by T-REX-XP** [comment]
Hello. You can run three copy of this container with different configuration))

**Comment by arthurkrupa** [comment]
@Nasserish try to remove the addon AND the repository from Hassio, then restart your host device. Add the repo again and make sure you install v1.0.4.

I've ran into similar issues a couple of days ago, because a NodeJS version was removed from Alpine Linux repositories, so the addon wouldn't build.

If you have SSH access (using the addon) to your Hassio, sometimes restarting Supervisor helps with addon issues (`hassio su reload`).

**Comment by Nasserish** [comment]
I've tried uninstalling the addon then reinstall it again, but now I'm not able to build more than one container.

What's weird is when I installed the addon the second time, all of my addon page disappeared until I added your respiratory again. 

Any advice? 
Thanks

**Comment by Nasserish** [comment]
I've tried restoring a partial snapshot, but no luck..

**Comment by arthurkrupa** [comment]
I've never tried to run multiple instances of the same addon at once. Is this even supported by Hass.io?

You could try to manually put the code inside the `/addons/` directory (as described [here](https://developers.home-assistant.io/docs/en/hassio_addon_tutorial.html)) and then duplicate it (e.g. `/addons/gree-1/`, `/addons/gree-2/`). This would skip the repository part.

BTW if you have problems with Home Assistant after removing a repository, try to reload Hassio Supervisor (as mentioned [here](https://github.com/arthurkrupa/gree-hvac-mqtt-bridge/issues/11#issuecomment-403082138)).

**Comment by Nasserish** [comment]
I added the addon manually and it works great. However the AC current temperature is a replicate of the target temperature.
I'm not sure if there's a sensor in gree. 

Many thanks

**Comment by dragonflyuk** [comment]
I can confirm that using the methods outlined here I have successfully added 4 units to the same hass.io config. If you are keeping a list of compatible model mine are all Cooper+Hunter models I can dig out the model numbers if they help anyone.

**Comment by arthurkrupa** [comment]
Multiple devices can now be added using the Hassio addon (fe31cf8025b2f1a0c6772eaa908a9feb49880dad). Please update to v1.2.0.
