### ISSUE TITLE
Running this with Homeassistant directly

### ISSUE THREAD

**Issue by gcosta74** [arthurkrupa/gree-hvac-mqtt-bridge#14]
Hi there,

Is there any chance torun this with home assistant directly ?

I mean without having hass.io and docker option.

Giuseppe

**Comment by arthurkrupa** [comment]
It's a simple NodeJS service, so you simply need to run it anywhere (e.g. your HA host) with the correct environment variables (have a look at `run.sh` for guidance).

You should also use a process manager like [PM2](http://pm2.keymetrics.io/) to handle restarts/crashes.

**Comment by gcosta74** [comment]
Thank You for the Help. Works like a charm.
The only thing is the operation_mode setting to "none". In HA the status "none" will not be recognized as off. Also the swing_mode to default is a little bit confusing, since default would mean off in my HVAC.

The services climate_turn_on and climate turn_off do not work and instead the service climate.set_operation_mode has to be used. This is only a minor problem.

**Comment by arthurkrupa** [comment]
I agree, this is confusing, but it is also intended. Back when I was implementing the service, there was no way to turn an MQTT HVAC device on or off through Hass.io. Using an additional "mode" was the only workaround I found.

If this is something that has changed in the meantime, please feel free to open a new issue with this request.
