### ISSUE TITLE
Extra functionality

### ISSUE THREAD

**Issue by knackrack615** [arthurkrupa/gree-hvac-mqtt-bridge#18]
Hello, the bridge works great so far but i'd like to see support for the extra AC functionality

Extra functionality includes:

- Turbo
- Air (Pulls air from outside)
- Dry/X-Fan (Keeps the AC fan on for a few mins to dry the AC after running in cooling mode for a while)
- Health (Enables the ioniser)
- Power Saving (Not exactly sure what this does)

The people at OpenHAB have already made a binding with all the extras i've mentioned above

Forum link: https://community.openhab.org/t/new-gree-air-conditioner-binding/36429
OpenHAB Binding: https://github.com/jllcunha/openhab-greeair-binding/

Would be great if we could get this functionality on HA :)

Edit: i just realised that there's already a pull request for this functionality ( #13 ) but it hasn't been updated since 22 Jul

**Comment by arthurkrupa** [comment]
Please update to 1.1.0 and check if the features work.

**Comment by kajobert** [comment]
Hello,
first of all thanks for this great project Works like a charm, now i can use node-red to automatically controll my AC :)
Im just missing "Turbo" mode. It is useful when You need quickly heat the room when You arrive at home. Im using it a lot.
In "commandEnums.js" is "turbo" function, so You can add this easilly.

I added it by myself, and it works.

//sry for my bad english
