### ISSUE TITLE
Home Assistant shows "Invalid mode: off"

### ISSUE THREAD

**Issue by bboti86** [arthurkrupa/gree-hvac-mqtt-bridge#26]
Hi! 

Hass keeps showing me these errors in the log file: 
2019-03-14 01:15:44 ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid mode: off
As you can see it is quite common: 
Invalid mode: off
1:24 components/mqtt/climate.py (ERROR) - message first occured at 1:22 and shows up 45 times 
this was generated in a couple minutes only. 
Could you please look into it? 
There is nothing in the add-on's log. 

Thanks! 
B

**Comment by arthurkrupa** [comment]
Please see if #19 helps.

Also, there have been lots of breaking changes in latest Hass.io releases. I've intentionally stopped upgrading so I don't have to check my config each time. Maybe there was a change in the climate component and the config example in the Readme has become invalid.

**Comment by bboti86** [comment]
Hey @arthurkrupa, 
I realized that I kept copying an old config file and the name of the states where changed in the meantime. 
Now it works completely.
Thanks! 
B
