### ISSUE TITLE
Help installing addon in Hassio

### ISSUE THREAD

**Issue by dragonflyuk** [arthurkrupa/gree-hvac-mqtt-bridge#27]
I'm trying to install the addon on my hassio install, however I'm a little confused by the step at https://github.com/arthurkrupa/gree-hvac-mqtt-bridge#running-addon-locally 
Do I need to add the code to my hassio options.json file, as it looks a completely different format.

Thanks

**Comment by arthurkrupa** [comment]
This step is for developers if they want to run the bridge on their computer (for testing, debugging).

What you're looking for is this guide: https://github.com/arthurkrupa/gree-hvac-mqtt-bridge#hassio-addon

**Comment by dragonflyuk** [comment]
Thanks, I've followed those steps, but I appear to be not getting any proper comunication, I can see the messages over MQTT and I can post message and the unit responds, but hassio, appears to neither send messages or read those from the unit/bridge. Any ideas?
