### ISSUE TITLE
Adding Light, Health, Sleep to hassio

### ISSUE THREAD

**Issue by dragonflyuk** [arthurkrupa/gree-hvac-mqtt-bridge#30]
Is it possible to add the Health, Sleep and Light options to hassio, Iguess they aren't added because they aren't part of the standard climate control. Does that mean it's best to add them as switches?

**Comment by dragonflyuk** [comment]
If it helps anyone I have them working 

`  - platform: mqtt
    name: "Living Room AC Light"
    command_topic: "home/greehvac/lights/set"
    state_topic: "home/greehvac/lights/get"
    qos: 1
    state_on: "on"
    state_off: "off"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Living Room AC Health"
    command_topic: "home/greehvac/health/set"
    state_topic: "home/greehvac/health/get"
    qos: 1
    state_on: "on"
    state_off: "off"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Living Room AC Sleep Mode"
    command_topic: "home/greehvac/sleep/set"
    state_topic: "home/greehvac/sleep/get"
    qos: 1
    state_on: "on"
    state_off: "off"
    payload_on: "1"
    payload_off: "0"
`

**Comment by dragonflyuk** [comment]
I'm sure someone more creative can do better, but I slapped this together:

type: vertical-stack
cards:
  - type: thermostat
    entity: climate.bedroom_upstairs_ac
  - type: horizontal-stack
    cards:
      - type: entity-button
        entity: switch.bedroom_upstairs_ac_light
        name: Light
      - type: entity-button
        entity: switch.bedroom_upstairs_ac_health
        name: Health
      - type: entity-button
        entity: switch.bedroom_upstairs_ac_sleep_mode
        name: Sleep Mode

**Comment by arthurkrupa** [comment]
Your workaround seems to be the only way to support these settings for now. I'm closing this issue because it's not directly related to this project.
