### ISSUE TITLE
Publish only the changes

### ISSUE THREAD

**Issue by roleee** [arthurkrupa/gree-hvac-mqtt-bridge#35]
Is it necessary to publish 374400 mqtt-message daily? 13 publish every 3 seconds.

Proposal:
[index.zip]
(https://github.com/arthurkrupa/gree-hvac-mqtt-bridge/files/3109528/index.zip)

`var last_temperature = '';`

`if(last_temperature != deviceModel.props[commands.temperature.code].toString()){`
`  client.publish(mqttTopicPrefix + '/temperature/get', deviceModel.props[commands.temperature.code].toString());`
`  last_temperature = deviceModel.props[commands.temperature.code].toString();`
`}`

**Comment by arthurkrupa** [comment]
Yes, this could be improved. I won't have time in the near future to add this, but you're welcome to file a PR.

**Comment by arthurkrupa** [comment]
Fixed by #36
