### ISSUE TITLE
Is it needed to configure it?

### ISSUE THREAD

**Issue by mihaiblaga89** [arthurkrupa/gree-hvac-mqtt-bridge#4]
Hello,

First of all, you just saved me a whole lot of time, I was trying to reverse engineer the communication as well to integrate my A/C with Google Home. 

The question is, I already "paired" the A/C with the app and I would like the app to continue to function in parallel with this integration. Is it really necessary to reset the WiFi and pair it again?

Thanks,
Mihai

**Comment by arthurkrupa** [comment]
If the AC is already connected to your WiFi (not your phone's hotspot) and you know its IP address, you should be fine. The Readme instructions are for people who can't use the mobile app (which was my case).
