### ISSUE TITLE
Extract HVAC logic to a separate package

### ISSUE THREAD

**Issue by aivus** [arthurkrupa/gree-hvac-mqtt-bridge#40]
Hi Arthur and thank you for this great repo.

I'm going to implement integration Gree HVAC with Homey and reuse HVAC logic from this repo. But this repo has not only interaction logic but mqtt bridge as well.

It will be good to have bridge and HVAC interaction logic (from `app` directory) in separate modules.

I know that I still can use your module and use only `deviceFactory` in my module but it will have additional not used functional.

What do you think about separating logic?

**Comment by arthurkrupa** [comment]
Hi Ilya.

A quick fix would be to subdivide the `deviceFactory` into smaller exportable es6 modules. Then you could only use the stuff you need and skip the rest.

In the long term, a separate library (with npm package) would be the way to go. Unfortunately, I won't have the time to maintain a separate code base in the near future, but I would welcome if someone else did!

**Comment by inwaar** [comment]
Hi guys, I've extracted logic into a separate lib for my own needs - https://github.com/inwaar/gree-hvac-client

**Comment by danieletdg** [comment]
@inwaar 
tremendous man!
This also works with my daitsu hvac. I was sure the Gree had the same wifi module as my Daitsu!
@arthurkrupa I can't understand why I can't get your script to work with my hvac. Very Strange!

Anyway.. Great Jobs Guys! Very impressive.

Daniele.

**Comment by aivus** [comment]
I'm closing this issue as we have https://github.com/inwaar/gree-hvac-client
