### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by ivgg-me** [arthurkrupa/gree-hvac-mqtt-bridge#8]
Is this project compatible with the Gree HVAC GWH12ACC and GWH09QB? Each of those have Wi-Fi on board.

Thank you!

**Comment by arthurkrupa** [comment]
I'm not sure. I have only tested it on a Sinclair Zoom Series (ASH-09AIZ, ASH-13AIZ, ASH-18AIZ, ASH-24AIZ), which use Gree's communication protocol.

**Comment by T-REX-XP** [comment]
I have got Cooper & Hunter nordic evo 2(CH-s09FTXN-e2wf) AC. Is it possible to add support it??
Here is some user manual - [http://cooperandhunter.com/ua/nordic_evo_two_instruction.pdf](url)
play market app - [https://play.google.com/store/apps/details?id=net.conditioner.web](url)

**Comment by arthurkrupa** [comment]
Please see #9.
