### ISSUE TITLE
Add support for Cooper&Hunter

### ISSUE THREAD

**Issue by T-REX-XP** [arthurkrupa/gree-hvac-mqtt-bridge#9]
Hello, after some researching i found the sources of android app (it was writen on apache cordova )

Could you please add support the new AC 

Here is full sources on JavaScript: [https://app.box.com/s/8eyj70vholfrl8lc4ib2mjf04sf86ejh](url)

Please contact me when you need some additional info.
Thanks.

**Comment by arthurkrupa** [comment]
This is outside of the scope of this app. I don't plan to add other protocols than Gree. You can always fork the repo and adjust it for you AC.
